version: '3'
services:
  mongo:
    image: mongo:3.6.11
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db

  kafka-cluster:
    image: landoop/fast-data-dev:2.3.0
    container_name: kafka
    environment:
      - DISABLE=azure-documentdb,blockchain,bloomberg,coap,druid,ftp,hazelcast,influxdb,jms,kudu,mqtt,rethink,voltdb,yahoo
      - ADV_HOST=127.0.0.1
      - RUNTESTS=0
    ports:
      - 2181:2181 # Zookeeper
      - 3030:3030 # Landoop UI
      - 8081-8083:8081-8083 # REST Proxy, Schema Registry, Kafka Connector
      - 9092:9092 # Kafka Broker
